name: Around Oracle
description: >
    Блог по технологиям Oracle
about: >
    Oracle blog, Oracle developer, Apex.

master_repo: false
url: "https://sysnord.github.io/"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           whitepaper
  avatar:         "https://sun9-45.userapi.com/c853424/v853424168/1236f9/bB5N92zGPkU.jpg"
  email:          "sysnord@gmail.com"
  # Social networking links used in footer. Update and remove as you like.  
  github: https://github.com/sysnord  
  linkedin: https://www.linkedin.com/in/sysnord/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
